fundamental_test: indentation

diff --git a/test/fundamental_test b/test/fundamental_test
--- a/test/fundamental_test
+++ b/test/fundamental_test
@@ -38,102 +38,102 @@ cp ../testing.bash "$TEST_WORKDIR/"
 cp "$FUNDAMENTAL_TEST_FILE" "$TEST_WORKDIR/"
 
 (
-cd "$TEST_WORKDIR"
-export GOT_SINGLE="GOT_SINGLE"
-export GOT_ALL="GOT_ALL"
-
-# Write the result of ./$FUNDAMENTAL_TEST_FILE to GOT_SINGLE.
-# Use NOTIME=YES because timer output is unpredicable and we want to check
-# for an exact output.
-(
-  # shellcheck disable=SC2030 disable=SC2031
-  export VERBOSE=YES NOTIME=YES TESTING_BASH=testing.bash
-  "./$FUNDAMENTAL_TEST_FILE" 2>&1 | tee "$GOT_SINGLE" | sed "s/^/$FUNDAMENTAL_TEST_FILE (single): /g" > /dev/stdout
-) || true
-
-# Write the result of ./testing.bash to GOT_ALL.
-(
-  # shellcheck disable=SC2030 disable=SC2031
-  export VERBOSE=YES NOTIME=YES TESTING_BASH=testing.bash
-  ./testing.bash "$FUNDAMENTAL_TEST_FILE" 2>&1 | tee "$GOT_ALL" | sed "s/^/$FUNDAMENTAL_TEST_FILE (runner): /g" > /dev/stdout
-) || true
-
-# Let's check our assumptions to be extra safe.
-diff "$GOT_SINGLE" "$GOT_SINGLE" || {
-  echo "    diff not behaving as expected! diff $GOT_SINGLE $GOT_SINGLE not empty!"
-  exit 1
-}
-diff "$GOT_ALL" "$GOT_ALL" || {
-  echo "    diff not behaving as expected! diff $GOT_ALL $GOT_ALL not empty!"
-  exit 1
-}
-if ! $UPDATE_EXPECTED; then
-diff "$WANT" "$WANT" || {
-  echo "    diff not behaving as expected! diff $WANT $WANT not empty!"
-  exit 1
-}
-fi
-
-FAILED=NO
-
-# If these files are different, then we have failed.
-# Eyeball this failure, sometimes you'll need to update
-# expectations in the WANT file above
-echo "=== RUN   fundamental/single=all"
-if ! diff "$GOT_SINGLE" "$GOT_ALL"; then
-  echo "--- FAIL: fundamental/single=all"
-  echo "    Diff not empty, see above."
-  echo "    Got:"
-  sed 's/^/    /g' < "$GOT_SINGLE"
-  echo "    Want:"
-  sed 's/^/    /g' < "$GOT_ALL"
-  FAILED=YES
-  # If we are trying to update expected, let's at least ensure we got the
-  # same output both times.
-  $UPDATE_EXPECTED && {
-    echo "Failed to update $WANT: all and single had different outputs."
-    exit 1
-  }
-else
-  echo "--- PASS: fundamental/single=all"
-  # OK, we got the same results, we are allowed to update expectations.
-  $UPDATE_EXPECTED && {
-    cp "$GOT_SINGLE" "$WANT"
-  }
-fi
-
-echo "=== RUN   fundamental/single=want"
-if ! diff "$GOT_SINGLE" "$WANT"; then
-  echo "--- FAIL: fundamental/single=want"
-  echo "    Diff not empty, see above."
-  echo "    Got:"
-  sed 's/^/    /g' < "$GOT_SINGLE"
-  echo "    Want:"
-  sed 's/^/    /g' < "$WANT"
-  FAILED=YES
-else
-  echo "--- PASS: fundamental/single=want"
-fi
-
-echo "=== RUN   fundamental/all=want"
-if ! diff "$GOT_ALL" "$WANT"; then
-  echo "--- FAIL: fundamental/ALL"
-  echo "    Diff not empty, see above."
-  echo "    Got:"
-  sed 's/^/    /g' < "$GOT_ALL"
-  echo "    Want:"
-  sed 's/^/    /g' < "$WANT"
-  FAILED=YES
-else
-  echo "--- PASS: fundamental/all=want"
-fi
-
-[ $FAILED = NO ] || {
-  echo "FAIL"
-  echo "exit status 1"
-  echo "FAIL      fundamental"
-  exit 1
-}
-echo "PASS"
-echo "ok        fundamental"
+	cd "$TEST_WORKDIR"
+	export GOT_SINGLE="GOT_SINGLE"
+	export GOT_ALL="GOT_ALL"
+	
+	# Write the result of ./$FUNDAMENTAL_TEST_FILE to GOT_SINGLE.
+	# Use NOTIME=YES because timer output is unpredicable and we want to check
+	# for an exact output.
+	(
+	  # shellcheck disable=SC2030 disable=SC2031
+	  export VERBOSE=YES NOTIME=YES TESTING_BASH=testing.bash
+	  "./$FUNDAMENTAL_TEST_FILE" 2>&1 | tee "$GOT_SINGLE" | sed "s/^/$FUNDAMENTAL_TEST_FILE (single): /g" > /dev/stdout
+	) || true
+	
+	# Write the result of ./testing.bash to GOT_ALL.
+	(
+	  # shellcheck disable=SC2030 disable=SC2031
+	  export VERBOSE=YES NOTIME=YES TESTING_BASH=testing.bash
+	  ./testing.bash "$FUNDAMENTAL_TEST_FILE" 2>&1 | tee "$GOT_ALL" | sed "s/^/$FUNDAMENTAL_TEST_FILE (runner): /g" > /dev/stdout
+	) || true
+	
+	## Let's check our assumptions to be extra safe.
+	#diff "$GOT_SINGLE" "$GOT_SINGLE" || {
+	#  echo "    diff not behaving as expected! diff $GOT_SINGLE $GOT_SINGLE not empty!"
+	#  exit 1
+	#}
+	#diff "$GOT_ALL" "$GOT_ALL" || {
+	#  echo "    diff not behaving as expected! diff $GOT_ALL $GOT_ALL not empty!"
+	#  exit 1
+	#}
+	#if ! $UPDATE_EXPECTED; then
+	#diff "$WANT" "$WANT" || {
+	#  echo "    diff not behaving as expected! diff $WANT $WANT not empty!"
+	#  exit 1
+	#}
+	#fi
+	
+	FAILED=NO
+	
+	# If these files are different, then we have failed.
+	# Eyeball this failure, sometimes you'll need to update
+	# expectations in the WANT file above
+	echo "=== RUN   fundamental/single=all"
+	if ! diff "$GOT_SINGLE" "$GOT_ALL"; then
+	  echo "--- FAIL: fundamental/single=all"
+	  echo "    Diff not empty, see above."
+	  echo "    Got:"
+	  sed 's/^/    /g' < "$GOT_SINGLE"
+	  echo "    Want:"
+	  sed 's/^/    /g' < "$GOT_ALL"
+	  FAILED=YES
+	  # If we are trying to update expected, let's at least ensure we got the
+	  # same output both times.
+	  $UPDATE_EXPECTED && {
+	    echo "Failed to update $WANT: all and single had different outputs."
+	    exit 1
+	  }
+	else
+	  echo "--- PASS: fundamental/single=all"
+	  # OK, we got the same results, we are allowed to update expectations.
+	  $UPDATE_EXPECTED && {
+	    cp "$GOT_SINGLE" "$WANT"
+	  }
+	fi
+	
+	echo "=== RUN   fundamental/single=want"
+	if ! diff "$GOT_SINGLE" "$WANT"; then
+	  echo "--- FAIL: fundamental/single=want"
+	  echo "    Diff not empty, see above."
+	  echo "    Got:"
+	  sed 's/^/    /g' < "$GOT_SINGLE"
+	  echo "    Want:"
+	  sed 's/^/    /g' < "$WANT"
+	  FAILED=YES
+	else
+	  echo "--- PASS: fundamental/single=want"
+	fi
+	
+	echo "=== RUN   fundamental/all=want"
+	if ! diff "$GOT_ALL" "$WANT"; then
+	  echo "--- FAIL: fundamental/ALL"
+	  echo "    Diff not empty, see above."
+	  echo "    Got:"
+	  sed 's/^/    /g' < "$GOT_ALL"
+	  echo "    Want:"
+	  sed 's/^/    /g' < "$WANT"
+	  FAILED=YES
+	else
+	  echo "--- PASS: fundamental/all=want"
+	fi
+	
+	[ $FAILED = NO ] || {
+	  echo "FAIL"
+	  echo "exit status 1"
+	  echo "FAIL      fundamental"
+	  exit 1
+	}
+	echo "PASS"
+	echo "ok        fundamental"
 )
